/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.vehicle.views;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author elmonazareno
 */
@Template(CrudFormPage.class)
public class VehicleDriverPage extends javax.swing.JPanel {

    /**
     * Creates new form VehicleDriverPage
     */
    public VehicleDriverPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();
        entityAddressLookup1 = new com.rameses.entity.components.EntityAddressLookup();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xButton1 = new com.rameses.rcp.control.XButton();

        xFormPanel3.setCaptionWidth(150);

        xTextField1.setCaption("Control No");
        xTextField1.setDisableWhen("#{ mode != 'create' }");
        xTextField1.setName("entity.controlno"); // NOI18N
        xFormPanel3.add(xTextField1);

        xLabel4.setCaption("Control No");
        xLabel4.setExpression("#{entity.controlno}");
        xLabel4.setVisibleWhen("#{ false }");
        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel4.setPreferredSize(new java.awt.Dimension(150, 20));
        xFormPanel3.add(xLabel4);

        xLabel1.setCaption("");
        xLabel1.setExpression("Leave controlno as blank to generate automated number");
        xLabel1.setVisibleWhen("#{ mode == 'create' }");
        xFormPanel3.add(xLabel1);

        entityLookup1.setCaption("Driver Name");
        entityLookup1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        entityLookup1.setEntityType("individual");
        entityLookup1.setName("entity.entity"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 21));
        entityLookup1.setRequired(true);
        xFormPanel3.add(entityLookup1);

        entityAddressLookup1.setCaption("Home Address");
        entityAddressLookup1.setDepends(new String[] {"entity.entity"});
        entityAddressLookup1.setName("entity.entity.address"); // NOI18N
        entityAddressLookup1.setParentIdName("entity.entity.objid");
        entityAddressLookup1.setPreferredSize(new java.awt.Dimension(0, 40));
        entityAddressLookup1.setRequired(true);
        xFormPanel3.add(entityAddressLookup1);

        xLookupField1.setCaption("Unit");
        xLookupField1.setExpression("Plateno: #{ entity.unit.plateno } Body No:#{ entity.unit.bodyno }");
        xLookupField1.setHandler("vw_vehicle_unit:lookup");
        xLookupField1.setName("entity.unit"); // NOI18N
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField1.setRequired(true);
        xFormPanel3.add(xLookupField1);

        xButton1.setCaption("");
        xButton1.setDepends(new String[] {"entity.unit"});
        xButton1.setName("viewUnit"); // NOI18N
        xButton1.setVisibleWhen("#{ entity.unit != null }");
        xButton1.setImmediate(true);
        xButton1.setText("View Unit");
        xFormPanel3.add(xButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.entity.components.EntityAddressLookup entityAddressLookup1;
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
