/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.vehicle.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class VehicleApplicationSearchPage extends javax.swing.JPanel {

    /**
     * Creates new form SpecifyFranchiseControlNoPage
     */
    public VehicleApplicationSearchPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();

        xRadio1.setName("searchOption"); // NOI18N
        xRadio1.setOptionValue("controlno");
        xRadio1.setShowCaption(false);
        xRadio1.setText("By Control No");
        xRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRadio1ActionPerformed(evt);
            }
        });
        xFormPanel2.add(xRadio1);

        xTextField1.setCaption("Control No");
        xTextField1.setDepends(new String[] {"searchOption"});
        xTextField1.setName("controlno"); // NOI18N
        xTextField1.setVisibleWhen("#{ searchOption == 'controlno' }");
        xTextField1.setCaptionWidth(100);
        xTextField1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField1.setPreferredSize(new java.awt.Dimension(250, 20));
        xFormPanel2.add(xTextField1);

        xRadio2.setName("searchOption"); // NOI18N
        xRadio2.setOptionValue("owner");
        xRadio2.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xRadio2.setShowCaption(false);
        xRadio2.setText("By Owner");
        xFormPanel2.add(xRadio2);

        entityLookup1.setCaption("Owner");
        entityLookup1.setCaptionWidth(100);
        entityLookup1.setCellPadding(new java.awt.Insets(0, 25, 0, 0));
        entityLookup1.setDepends(new String[] {"searchOption"});
        entityLookup1.setEntityType("entityindividual");
        entityLookup1.setName("owner"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 21));
        entityLookup1.setRequired(true);
        entityLookup1.setVisibleWhen("#{ searchOption == 'owner' }");
        xFormPanel2.add(entityLookup1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRadio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xRadio1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
