UPDATE vehicle_franchise SET appid = null,unitid=null, acctid=null,permitid = null;
UPDATE vehicle_application SET unitid=null, acctid=null, taskid = NULL;
DELETE FROM vehicle_permit;
DELETE FROM vehicle_payment_item;
DELETE FROM vehicle_payment;
DELETE FROM vehicle_application_task;
DELETE FROM vehicle_application_fee;
DELETE FROM vehicle_application_info;
DELETE FROM vehicle_unit_info;
DELETE FROM vehicle_unit;
DELETE FROM vehicle_application;
DELETE FROM vehicle_franchise;
UPDATE vehicle_itemaccount SET item_objid = NULL, item_title = null, item_code = null, item_fund_objid = null; 
DELETE FROM sys_sequence;
