/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.vehicle.components;

import com.rameses.common.PropertyResolver;
import com.rameses.rcp.control.XComponentPanel;
import com.rameses.rcp.ui.annotations.ComponentBean;

/**
 *
 * @author elmonazareno
 */
@ComponentBean("com.rameses.gov.etracs.vehicle.components.VehicleUnitListComponent")
public class VehicleUnitList extends XComponentPanel {

    private String vehicletype;
    private String items;
    private String handler;
    
    
    /**
     * Creates new form VehicleUnitList
     */
    public VehicleUnitList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        dataTable = new com.rameses.rcp.control.XDataTable();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        dataTable.setHandler("unitListModel");
        dataTable.setItems("");
        dataTable.setName("value"); // NOI18N
        jPanel2.add(dataTable, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDataTable dataTable;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
// </editor-fold>   

    @Override
    protected void initComponentBean(com.rameses.rcp.common.ComponentBean bean) {
        bean.setProperty("vehicletype", getProperty(getVehicletype() ) );
        bean.setProperty("items",  getProperty(getItems()) );
        Object callerBean = super.getBinding().getBean();
        PropertyResolver.getInstance().setProperty(callerBean, getHandler(), bean.getProperty("unitListModel"));
    } 
      
   /* 
    @Override
    public void afterLoad() {
        com.rameses.rcp.common.ComponentBean bean = (com.rameses.rcp.common.ComponentBean)getComponentBean(); 
        try {
            MethodResolver.getInstance().invoke(bean, "init", null);
        }
        catch(Exception ex) {
            MsgBox.err(ex);
        }
    }
    */

    /**
     * @return the vehicletype
     */
    public String getVehicletype() {
        return vehicletype;
    }

    /**
     * @param vehicletype the vehicletype to set
     */
    public void setVehicletype(String vehicletype) {
        this.vehicletype = vehicletype;
    }

    /**
     * @return the items
     */
    public String getItems() {
        return items;
    }

    /**
     * @param items the items to set
     */
    public void setItems(String items) {
        this.items = items;
    }

    /**
     * @return the handler
     */
    public String getHandler() {
        return handler;
    }

    /**
     * @param handler the handler to set
     */
    public void setHandler(String handler) {
        this.handler = handler;
    }

    
    
}
